CREATE TABLE `EMPLEADO` (
  `COD_EMPLE` int PRIMARY KEY,
  `NOMBRES` varchar(50) NOT NULL,
  `APELLIDOS` varchar(50) NOT NULL,
  `DNI_EMPLE` char(8) UNIQUE NOT NULL,
  `ESTADO_CIVIL` varchar(15),
  `NIVEL_EDUCA` varchar(25),
  `TELEFONO` varchar(15),
  `EMAIL` varchar(50) UNIQUE,
  `FECHA_INGRESO` date NOT NULL,
  `ID_DIRECCION` int NOT NULL,
  `COD_CARGO` int NOT NULL,
  `COD_SEDE` int NOT NULL
);

CREATE TABLE `DIRECCION` (
  `ID_DIRECCION` int PRIMARY KEY,
  `DEPARTAMENTO` varchar(30) NOT NULL,
  `PROVINCIA` varchar(30) NOT NULL,
  `DETALLE_DIRECCION` varchar(70) NOT NULL,
  `REFERENCIA` varchar(80)
);

CREATE TABLE `CLIENTE` (
  `ID_CLIENTE` int PRIMARY KEY,
  `NOMBRES` varchar(30) NOT NULL,
  `APELLIDOS` varchar(40) NOT NULL,
  `FONO` varchar(15),
  `ID_DIRECCION` int NOT NULL,
  `EMAIL` varchar(50)
);

CREATE TABLE `BOLETA` (
  `NUM_BOLETA` int PRIMARY KEY,
  `FECHA_EMI` date NOT NULL,
  `ID_CLIENTE` int NOT NULL,
  `COD_EMPLE` int NOT NULL,
  `ESTADO_BOLETA` enum(PENDIENTE,PAGADO,ANULADO) NOT NULL
);

CREATE TABLE `CARGOS` (
  `COD_CARGO` int PRIMARY KEY,
  `NOMBRE_CARGO` varchar(50) NOT NULL,
  `SUELDO_BASICO` decimal NOT NULL
);

CREATE TABLE `PRODUCTO` (
  `ID_PRODUCTO` char(6) PRIMARY KEY,
  `DESCRIPCION` varchar(100) NOT NULL,
  `PRECIO_VENTA` decimal NOT NULL,
  `STOCK_MINIMO` int NOT NULL,
  `STOCK_ACTUAL` int NOT NULL,
  `COD_CATE` char(6) NOT NULL,
  `COD_SEDE` int NOT NULL
);

CREATE TABLE `CATEGORIAS` (
  `COD_CATE` char(6) PRIMARY KEY,
  `NOMBRE` varchar(30) NOT NULL
);

CREATE TABLE `DETALLEBOLETA` (
  `NUM_BOLETA` int NOT NULL,
  `ID_PRODUCTO` char(6) NOT NULL,
  `CANTIDAD` int NOT NULL,
  `IMPORTE` decimal NOT NULL
);

CREATE TABLE `SEDE` (
  `COD_SEDE` int PRIMARY KEY,
  `METROS2` decimal NOT NULL,
  `AFORO` int NOT NULL,
  `NUM_PISOS` int NOT NULL
);

CREATE TABLE `COMPLETO` (
  `COD_COMPLETO` int PRIMARY KEY,
  `COD_EMPLE` int NOT NULL,
  `ID_DIRECCION` int NOT NULL,
  `ID_CLIENTE` int NOT NULL
);

ALTER TABLE `EMPLEADO` ADD FOREIGN KEY (`COD_CARGO`) REFERENCES `CARGOS` (`COD_CARGO`);

ALTER TABLE `EMPLEADO` ADD FOREIGN KEY (`ID_DIRECCION`) REFERENCES `DIRECCION` (`ID_DIRECCION`);

ALTER TABLE `EMPLEADO` ADD FOREIGN KEY (`COD_SEDE`) REFERENCES `SEDE` (`COD_SEDE`);

ALTER TABLE `CLIENTE` ADD FOREIGN KEY (`ID_DIRECCION`) REFERENCES `DIRECCION` (`ID_DIRECCION`);

ALTER TABLE `BOLETA` ADD FOREIGN KEY (`ID_CLIENTE`) REFERENCES `CLIENTE` (`ID_CLIENTE`);

ALTER TABLE `BOLETA` ADD FOREIGN KEY (`COD_EMPLE`) REFERENCES `EMPLEADO` (`COD_EMPLE`);

ALTER TABLE `DETALLEBOLETA` ADD FOREIGN KEY (`NUM_BOLETA`) REFERENCES `BOLETA` (`NUM_BOLETA`);

ALTER TABLE `DETALLEBOLETA` ADD FOREIGN KEY (`ID_PRODUCTO`) REFERENCES `PRODUCTO` (`ID_PRODUCTO`);

ALTER TABLE `PRODUCTO` ADD FOREIGN KEY (`COD_CATE`) REFERENCES `CATEGORIAS` (`COD_CATE`);

ALTER TABLE `PRODUCTO` ADD FOREIGN KEY (`COD_SEDE`) REFERENCES `SEDE` (`COD_SEDE`);

ALTER TABLE `EMPLEADO` ADD FOREIGN KEY (`COD_EMPLE`) REFERENCES `COMPLETO` (`COD_COMPLETO`);

ALTER TABLE `COMPLETO` ADD FOREIGN KEY (`COD_COMPLETO`) REFERENCES `DIRECCION` (`ID_DIRECCION`);

ALTER TABLE `COMPLETO` ADD FOREIGN KEY (`COD_COMPLETO`) REFERENCES `CLIENTE` (`ID_CLIENTE`);
